import { getDb, getEnv } from "./db";
import { findIdentity, fullAddress, type Identity } from "./identities";
import { recordSendRecipients } from "./contacts";

// Cloudflare's send_email binding has a structured-builder overload, so we
// don't need the `cloudflare:email` runtime module or mimetext at all — the
// binding builds MIME for us. Avoiding `cloudflare:email` also dodges a chain
// of bundler issues (esbuild can't resolve the Workers built-in, dynamic
// import gets compiled to require, code-from-strings is forbidden in the
// isolate, etc).

export interface SendInput {
  fromMailboxId: string;
  to: string[];
  cc?: string[];
  bcc?: string[];
  subject: string;
  body: string;
  replyToMessageId?: string;
  // If set, the draft is deleted in the same batch as the message insert.
  // The route validates ownership before passing it in.
  draftId?: string;
  // Outbound attachments staged via /api/uploads. We re-verify ownership and
  // pull bytes from R2 before handing them to env.EMAIL.send().
  attachmentIds?: string[];
}

export interface SendResult {
  messageId: string;
  threadId: string;
}

export async function sendMessage(userId: string, input: SendInput): Promise<SendResult> {
  const identity = await findIdentity(userId, input.fromMailboxId);
  if (!identity) throw new SendError("not_authorised", "You can't send from that mailbox.");
  if (identity.role === "reader") {
    throw new SendError("forbidden", "Your role on this domain is read-only.");
  }
  if (input.to.length === 0) throw new SendError("invalid", "At least one recipient is required.");

  const env = getEnv();
  const db = getDb();

  const { parentMessage, parentReferences } = await loadReplyParent(input.replyToMessageId);
  if (parentMessage && parentMessage.mailbox_id !== identity.mailbox_id) {
    // Reply must come from the mailbox that received the original — otherwise
    // threading would split. Surface this rather than silently moving threads.
    throw new SendError(
      "mailbox_mismatch",
      "Reply must use the mailbox the original was sent to.",
    );
  }

  const now = Math.floor(Date.now() / 1000);
  const messageId = crypto.randomUUID();
  const messageIdHeader = `<${messageId}@${identity.domain_name}>`;

  const fromAddr = fullAddress(identity);
  const fromName = identity.display_name?.trim() || undefined;

  // Cloudflare's send_email binding whitelists headers and rejects anything
  // not on the list. Message-ID and Date are auto-generated by the service
  // and rejected if we try to set them — In-Reply-To and References ARE
  // whitelisted and are what we need anyway for the recipient's client to
  // thread the reply. So we send those when this is a reply, and let
  // Cloudflare own Message-ID/Date.
  const headers: Record<string, string> = {};
  if (parentMessage) {
    headers["In-Reply-To"] = parentMessage.message_id_header;
    headers["References"] = [...parentReferences, parentMessage.message_id_header].join(" ");
  }

  // Resolve attachment uploads: validate ownership, pull bytes from R2, build
  // the EmailAttachment array. Done here (not in a helper) so a missing /
  // not-owned id surfaces a precise SendError before we touch the binding.
  const attachments: EmailAttachment[] = [];
  if (input.attachmentIds?.length) {
    for (const uploadId of input.attachmentIds) {
      const upload = await db
        .prepare(
          "SELECT id, filename, content_type, size, r2_key FROM temp_uploads WHERE id = ? AND user_id = ?",
        )
        .bind(uploadId, userId)
        .first<{ id: string; filename: string | null; content_type: string | null; size: number; r2_key: string }>();
      if (!upload) {
        throw new SendError("attachment_not_found", `Attachment ${uploadId} not found or not owned by you.`);
      }
      const obj = await env.ATTACHMENTS.get(upload.r2_key);
      if (!obj) {
        throw new SendError("attachment_missing", `Attachment ${upload.filename ?? uploadId} bytes are missing.`);
      }
      const buf = await obj.arrayBuffer();
      attachments.push({
        disposition: "attachment",
        filename: upload.filename || "attachment",
        type: upload.content_type || "application/octet-stream",
        content: buf,
      });
    }
  }

  const sendBuilder = {
    from: fromName ? { name: fromName, email: fromAddr } : fromAddr,
    to: input.to,
    cc: input.cc?.length ? input.cc : undefined,
    bcc: input.bcc?.length ? input.bcc : undefined,
    subject: input.subject || "(no subject)",
    text: input.body,
    ...(attachments.length > 0 ? { attachments } : {}),
    ...(Object.keys(headers).length > 0 ? { headers } : {}),
  } as const;
  try {
    await env.EMAIL.send(sendBuilder);
  } catch (e) {
    // Cloudflare's send_email error strings are sometimes generic ("internal
    // server error"). Log the full error object — message, name, cause, plus
    // the request payload that triggered it — so `wrangler tail` shows what
    // we actually need for diagnosis.
    console.error("env.EMAIL.send rejected", {
      error: serializeError(e),
      builder: { ...sendBuilder, text: `<${sendBuilder.text.length} chars>` },
    });
    const detail = e instanceof Error ? e.message : String(e);
    throw new SendError("send_failed", `Cloudflare rejected the send: ${detail}`);
  }

  // Persist a structured archive of what we sent. The send_email binding
  // doesn't return the raw MIME it built, so we save the structured fields
  // as JSON for debuggability — the schema's raw_r2_key column wants a
  // non-null path either way.
  const rawKey = `mailbox/${identity.mailbox_id}/${messageId}.json`;
  const archive = {
    from: fromName ? { name: fromName, email: fromAddr } : fromAddr,
    to: input.to,
    cc: input.cc ?? [],
    bcc: input.bcc ?? [],
    subject: input.subject,
    text: input.body,
    headers,
    sentAt: now,
  };
  await env.RAW_MAIL.put(rawKey, JSON.stringify(archive), {
    httpMetadata: { contentType: "application/json" },
    customMetadata: { mailbox: identity.mailbox_id, messageId, direction: "outbound" },
  });

  const threadId = parentMessage?.thread_id ?? crypto.randomUUID();
  const isNewThread = !parentMessage;
  const subjectNormalized = normalizeSubject(input.subject);
  const snippet = input.body.replace(/\s+/g, " ").trim().slice(0, 200);

  const stmts: D1PreparedStatement[] = [];
  if (isNewThread) {
    stmts.push(
      db
        .prepare(
          `INSERT INTO threads (id, mailbox_id, subject_normalized, last_message_at, message_count, unread_count)
           VALUES (?, ?, ?, ?, 0, 0)`,
        )
        .bind(threadId, identity.mailbox_id, subjectNormalized, now),
    );
  }

  stmts.push(
    db
      .prepare(
        `INSERT INTO messages
         (id, thread_id, mailbox_id, message_id_header, in_reply_to, references_chain,
          direction, from_addr, from_name, to_json, cc_json, bcc_json,
          subject, date, snippet, raw_r2_key, text_body, read, starred, sent_by_user_id)
         VALUES (?, ?, ?, ?, ?, ?, 'outbound', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 0, ?)`,
      )
      .bind(
        messageId,
        threadId,
        identity.mailbox_id,
        messageIdHeader,
        parentMessage?.message_id_header ?? null,
        parentMessage
          ? [...parentReferences, parentMessage.message_id_header].join(" ")
          : null,
        fromAddr,
        fromName ?? null,
        JSON.stringify(input.to.map(addr => ({ addr }))),
        input.cc?.length ? JSON.stringify(input.cc.map(addr => ({ addr }))) : null,
        input.bcc?.length ? JSON.stringify(input.bcc.map(addr => ({ addr }))) : null,
        input.subject || null,
        now,
        snippet,
        rawKey,
        input.body,
        userId,
      ),
  );

  // Outbound messages count toward message_count but never toward unread_count.
  stmts.push(
    db
      .prepare(
        `UPDATE threads
           SET message_count = message_count + 1,
               last_message_at = MAX(last_message_at, ?)
         WHERE id = ?`,
      )
      .bind(now, threadId),
  );

  if (input.draftId) {
    stmts.push(
      db
        .prepare("DELETE FROM drafts WHERE id = ? AND user_id = ?")
        .bind(input.draftId, userId),
    );
  }

  // Clean up the temp_uploads rows now that the message is on the wire.
  // The R2 blobs themselves are left for a future sweeper — they're harmless
  // orphans, and removing them in the hot send path would double the work.
  if (input.attachmentIds?.length) {
    const placeholders = input.attachmentIds.map(() => "?").join(",");
    stmts.push(
      db
        .prepare(
          `DELETE FROM temp_uploads WHERE user_id = ? AND id IN (${placeholders})`,
        )
        .bind(userId, ...input.attachmentIds),
    );
  }

  await db.batch(stmts);

  // Auto-add recipients to the mailbox's shared contact list. Best-effort —
  // a contact-store hiccup must never make a successful send look failed.
  try {
    const all = [
      ...input.to,
      ...(input.cc ?? []),
      ...(input.bcc ?? []),
    ].map(email => ({ email }));
    await recordSendRecipients(identity.mailbox_id, all);
  } catch (err) {
    console.error("contact auto-add failed", err);
  }

  return { messageId, threadId };
}

interface ParentInfo {
  parentMessage: {
    id: string;
    thread_id: string;
    mailbox_id: string;
    message_id_header: string;
    references_chain: string | null;
  } | null;
  parentReferences: string[];
}

async function loadReplyParent(parentId: string | undefined): Promise<ParentInfo> {
  if (!parentId) return { parentMessage: null, parentReferences: [] };
  const row = await getDb()
    .prepare(
      `SELECT id, thread_id, mailbox_id, message_id_header, references_chain
         FROM messages WHERE id = ?`,
    )
    .bind(parentId)
    .first<{
      id: string;
      thread_id: string;
      mailbox_id: string;
      message_id_header: string;
      references_chain: string | null;
    }>();
  if (!row) return { parentMessage: null, parentReferences: [] };
  const parentReferences = row.references_chain
    ? row.references_chain.split(/\s+/).filter(Boolean)
    : [];
  return { parentMessage: row, parentReferences };
}

function normalizeSubject(subject: string): string {
  let s = subject.trim();
  while (true) {
    const stripped = s.replace(/^\s*(?:re|fwd|fw|aw|tr|antw)\s*:\s*/i, "");
    if (stripped === s) break;
    s = stripped;
  }
  s = s.replace(/\s+/g, " ").trim().toLowerCase();
  return s || "(no subject)";
}

export class SendError extends Error {
  constructor(public code: string, message: string) {
    super(message);
  }
}

function serializeError(e: unknown): Record<string, unknown> {
  if (!(e instanceof Error)) return { value: String(e) };
  const out: Record<string, unknown> = {
    name: e.name,
    message: e.message,
    stack: e.stack,
  };
  // Include enumerable own properties (Cloudflare attaches `cause`, `code`,
  // sometimes a `response`-like shape).
  for (const key of Object.keys(e)) {
    out[key] = (e as unknown as Record<string, unknown>)[key];
  }
  if (e.cause !== undefined) out.cause = serializeError(e.cause);
  return out;
}

export type { Identity };
